services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    ports:
      - "16686:16686"     # Jaeger UI
      - "6831:6831/udp"   # Jaeger Agent (UDP)
      - "14250:14250"     # Jaeger Collector (gRPC)